---
- name: reload sysctl
  ansible.builtin.shell: |
    sysctl --system
  become: true

- name: reload udev
  ansible.builtin.shell: |
    udevadm control --reload-rules
    udevadm trigger --settle
  become: true
