---
- name: Ensure neovim is installed (Suse)
  community.general.zypper:
    name:
      - neovim
      - cargo
      - python3
      - rubygems
      - ruby-devel
      - go
    state: present
  become: true
