- name: Check if bash-preexec.sh already exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bash-preexec.sh"
  register: bash_preexec_stat

- name: Configure bash-preexec.sh
  when: not bash_preexec_stat.stat.exists
  block:
    - name: Download bash-preexec.sh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh
        dest: "{{ ansible_env.HOME }}/.bash-preexec.sh"
        mode: "0644"
        force: true

    - name: Disable __bp_adjust_histcontrol in bash-preexec.sh for atuin
      ansible.builtin.replace:
        path: "{{ ansible_env.HOME }}/.bash-preexec.sh"
        regexp: '^(\s+)(__bp_adjust_histcontrol)$'
        replace: '\1#\2 # disable due to https://github.com/rcaloras/bash-preexec/issues/115'

- name: Source bash-preexec.sh in .bashrc (before bashrc.d block)
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh"
    insertbefore: '^# BEGIN ANSIBLE MANAGED BLOCK - bashrc\.d$'
    create: true
    mode: "0644"
