---
- name: Create .bashrc.d directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
    mode: "0755"

- name: Ensure .bashrc.d/.ignore_me exists for stow logic
  ansible.builtin.copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.bashrc.d/.ignore_me"
    mode: "0644"

- name: Stow bash
  dandyrow.linux.stow:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_env.HOME }}"
    package: [bash]

- name: Add .bashrc.d sourcing block to .bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      if [ -d ~/.bashrc.d ]; then
      	for rc in ~/.bashrc.d/*; do
      		if [ -f "$rc" ]; then
      			. "$rc"
      		fi
      	done
      fi
      unset rc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - bashrc.d"
    create: true
    mode: "0644"

- name: Install dependencies (RedHat)
  include_tasks: ./redhat.yaml
  when: ansible_facts['os_family'] == "RedHat"

- name: Install dependencies (Suse)
  include_tasks: ./suse.yaml
  when: ansible_facts['os_family'] == "Suse"

- name: Install dependencies (Archlinux)
  include_tasks: ./archlinux.yaml
  when: ansible_facts['os_family'] == "Archlinux"

- name: Include ble.sh setup
  include_tasks: ./blesh.yaml
