---
- name: restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted
  become: true

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  become: true
