# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dc8fa92a-cae2-46ad-a15a-9072651a70b4";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/796E-6604";
      fsType = "vfat";
    };

  fileSystems."/mnt/home" =
    { device = "/dev/disk/by-uuid/2995333b-ee48-4ca1-b6e4-f446e7672622";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1356cc1d-222d-4297-8904-10bc6bec6aa8"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
