#!/bin/bash
SC_LOCATION="${HOME}/Pictures/Screenshots"

pngquant -f "${SC_LOCATION}/latest.png" --output "${SC_LOCATION}/low.png"

if [ $XDG_SESSION_TYPE = 'x11' ]; then
  xclip -selection clipboard -t image/png -i "${SC_LOCATION}/low.png"
else
  wl-copy < "${SC_LOCATION}/low.png"
fi
