#!/bin/bash
SC_LOCATION="${HOME}/Pictures/Screenshots"
SC_YEAR=$(date +%Y)
SC_MONTH=$(date +"%m %B")
SC_CURRENT_TIME="$(date +"%d %a %H:%M:%S")"

SC_DIR="${SC_LOCATION}/${SC_YEAR}/${SC_MONTH}"
SC_FILE="${SC_DIR}/${SC_CURRENT_TIME}.png"

mkdir -p "${SC_DIR}"

case $1 in
	maim)
		maim --select "${SC_FILE}"
		;;
    area)
        gnome-screenshot -a -f "${SC_FILE}"
        ;;
    window)
        gnome-screenshot -w -f "${SC_FILE}"
        ;;
    screen)
        gnome-screenshot -f "${SC_FILE}"
esac

if [ -f "${SC_FILE}" ]; then
    if [ $XDG_SESSION_TYPE = 'x11' ]; then
        xclip -selection clipboard -t image/png -i "${SC_FILE}"
    else
        wl-copy < "${SC_FILE}"
    fi
    ln -sf "${SC_FILE}" "${SC_LOCATION}/latest.png"
	if [ -f "$SC_LOCATION/low.png" ]; then
		'rm' "$SC_LOCATION/low.png"
	fi
fi
