---
- name: Ensure configured font families are installed (Archlinux)
  community.general.pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
    state: present
  become: true
