---
- name: Install (Suse)
  include_tasks: ./suse.yaml
  when: ansible_facts['os_family'] == "Suse"

- name: Install (Archlinux)
  include_tasks: ./archlinux.yaml
  when: ansible_facts['os_family'] == "Archlinux"
